### ISSUE TITLE
Integration with MQTT or Home Assistant

### ISSUE THREAD

**Issue by ernetas** [JUNGgroup/node-red-contrib-jung#2]
Is there an example of how to integrate Jung Home Gateway to MQTT or Home Assistant?

**Comment by JUNGgroup** [comment]
JUNG HOME Gateway has no _direct_ integration with MQTT or Home Assistant. Therefore no example exist.
JUNG HOME Gateway has integration to Node-RED and Node-RED has integrations and examples to MQTT ([https://cookbook.nodered.org/mqtt/connect-to-broker](https://cookbook.nodered.org/mqtt/connect-to-broker)) or to Home Assistant ([https://mikehillyer.com/home-automation/getting-started-with-home-assistant-and-node-red/](https://mikehillyer.com/home-automation/getting-started-with-home-assistant-and-node-red/)). Therefore integration can be achieved by using Node-RED as a central hub.
